-- Portada (hero) editable desde el panel: diapositivas + ajustes.
-- Ejecutar una vez en Supabase: SQL Editor -> New query -> pegar -> Run.

create table if not exists public.hero_slides (
  id integer generated by default as identity primary key,
  image_url text not null,
  mobile_image_url text,
  eyebrow text,
  title text,
  subtitle text,
  button_label text,
  button_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists hero_slides_set_updated_at on public.hero_slides;
create trigger hero_slides_set_updated_at before update on public.hero_slides
  for each row execute function public.set_updated_at();

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null
);

-- Solo el servidor (service role) accede; el navegador nunca toca estas tablas directo.
alter table public.hero_slides enable row level security;
alter table public.site_settings enable row level security;

-- Diapositiva actual de la marca (la que ya se ve hoy) y ajuste inicial.
insert into public.hero_slides (image_url, mobile_image_url, eyebrow, title, subtitle, button_label, button_url, sort_order)
select '/hero-bg.jpg', '/hero-bg-mobile.jpg', 'New Drop Available', 'BLACK SEVEN',
       'Streetwear & Underground Culture. Diseños exclusivos de edición limitada.',
       'Ver Colección', '/coleccion', 10
where not exists (select 1 from public.hero_slides);

insert into public.site_settings (key, value) values ('hero_show_products', 'true'::jsonb)
on conflict (key) do nothing;
