-- Catálogo de productos de BLACK SEVEN + almacenamiento de fotos.
-- Ejecutar una vez en Supabase: SQL Editor -> New query -> pegar -> Run.

create table if not exists public.products (
  id integer generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null check (price > 0),
  tag text,
  sizes text[] not null default '{}',
  images text[] not null default '{}',
  description text not null default '',
  details text[] not null default '{}',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products
  for each row execute function public.set_updated_at();

-- Solo el servidor (service role) accede a la tabla; el navegador nunca la toca directo.
alter table public.products enable row level security;

-- Productos actuales (mismos ids que ya usan carritos y pedidos existentes).
insert into public.products (id, name, category, price, tag, sizes, images, description, details, sort_order)
overriding system value
values
  (1, 'REMERA 777 WHITE', 'remeras', 35000, 'NEW', array['S', 'M', 'L', 'XL']::text[], array['/remera777.jpg', '/remera777hover.jpg']::text[], 'Confeccionada en algodón jersey 24/1 de pesado gramaje. Mantiene la forma y estructura con una caída boxy fit ideal para la cultura streetwear.', array['100% Algodón Jersey Heavyweight 240g', 'Estampa en serigrafía frente y espalda', 'Corte Boxy / Oversized Fit', 'Lavar con agua fría y del revés']::text[], 10),
  (2, 'REMERA BLK7 BLACK', 'remeras', 35000, 'HOT', array['M', 'L', 'XL']::text[], array['/remerablk7.jpg', '/remerablk7hover.jpg']::text[], 'Buzo de frisa invisible pesada con capucha de doble tela y bolsillo canguro. Diseñado para ofrecer máxima durabilidad y confort térmico.', array['Frisa invisible pesada 80/20', 'Bordado de alta densidad en el pecho', 'Puños y cintura de morley reinforced', 'Corte Relaxed Fit']::text[], 20),
  (3, 'CONJUNTO BLK 777', 'conjuntos', 68000, 'DROP', array['M', 'L', 'XL']::text[], array['/conjuntoblk777.jpg', '/conjuntoblk777hover.jpg']::text[], 'Buzo de frisa invisible pesada con capucha de doble tela y bolsillo canguro. Diseñado para ofrecer máxima durabilidad y confort térmico.', array['Frisa invisible pesada 80/20', 'Bordado de alta densidad en el pecho', 'Puños y cintura de morley reinforced', 'Corte Relaxed Fit']::text[], 30),
  (4, 'CAMPERA BLK 77', 'camperas', 52000, 'NEW', array['S', 'M', 'L']::text[], array['/camperablk77.jpg', '/camperablk77hover.jpg']::text[], 'Buzo de frisa invisible pesada con capucha de doble tela y bolsillo canguro. Diseñado para ofrecer máxima durabilidad y confort térmico.', array['Frisa invisible pesada 80/20', 'Bordado de alta densidad en el pecho', 'Puños y cintura de morley reinforced', 'Corte Relaxed Fit']::text[], 40),
  (5, 'CAMPERA BLACKSEVEN 77', 'camperas', 52000, 'GOD', array['S', 'M', 'L']::text[], array['/camperablackseven77.jpg', '/camperablackseven77hover.jpg']::text[], 'Buzo de frisa invisible pesada con capucha de doble tela y bolsillo canguro. Diseñado para ofrecer máxima durabilidad y confort térmico.', array['Frisa invisible pesada 80/20', 'Bordado de alta densidad en el pecho', 'Puños y cintura de morley reinforced', 'Corte Relaxed Fit']::text[], 50),
  (6, 'BUZO BLACKSEVEN 77', 'hoodies', 52000, 'NEW', array['S', 'M', 'L']::text[], array['/buzoblackseven77_1.jpg', '/buzoblackseven77_3.jpg', '/buzoblackseven77_2.jpg', '/buzoblackseven77hover.jpg']::text[], 'Buzo de frisa invisible pesada con capucha de doble tela y bolsillo canguro. Diseñado para ofrecer máxima durabilidad y confort térmico.', array['Frisa invisible pesada 80/20', 'Bordado de alta densidad en el pecho', 'Puños y cintura de morley reinforced', 'Corte Relaxed Fit']::text[], 60)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select max(id) from public.products), 1));

-- Espacio público para las fotos de productos (máx. 5 MB, solo imágenes).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('products', 'products', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

